import { NavGroup } from "@/types/navigation";

export const ADMIN_NAVIGATION: NavGroup[] = [
  {
    groupTitle: "Core Operations",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/admin/dashboard",
        iconName: "LayoutDashboard",
        permission: "dashboard.view",
      },
      {
        id: "users",
        label: "Users & Accounts",
        route: "/admin/users",
        iconName: "Users",
        permission: "users.view",
      },
      {
        id: "listings",
        label: "Listings Moderation",
        route: "/admin/listings",
        iconName: "Package",
        permission: "listings.view",
        badge: 184,
        badgeColor: "warning",
      },
      {
        id: "categories",
        label: "Categories & Schema",
        route: "/admin/categories",
        iconName: "FolderTree",
        permission: "categories.view",
      },
      {
        id: "stores",
        label: "Stores & Verification",
        route: "/admin/stores",
        iconName: "Store",
        permission: "stores.view",
        badge: 42,
        badgeColor: "info",
      },
      {
        id: "jobs",
        label: "Jobs Vertical",
        route: "/admin/jobs",
        iconName: "Briefcase",
        permission: "listings.view",
        badge: "NEW",
        badgeColor: "indigo",
      },
      {
        id: "services",
        label: "Services Vertical",
        route: "/admin/services",
        iconName: "Wrench",
        permission: "listings.view",
        badge: "NEW",
        badgeColor: "error",
      },
    ],
  },
  {
    groupTitle: "Promotions & Monetization",
    items: [
      {
        id: "promotions_overview",
        label: "Promotions & Boosts Workspace",
        route: "/admin/promotions",
        iconName: "Zap",
        permission: "promotions.view",
      },
      {
        id: "slot_specs",
        label: "Slot Specs (6)",
        route: "/admin/promotions/placements",
        iconName: "Layers",
        permission: "promotions.view",
      },
    ],
  },
  {
    groupTitle: "Advertisements (Display & Media)",
    items: [
      {
        id: "ads_overview",
        label: "Advertisements & Media Workspace",
        route: "/admin/ads",
        iconName: "Megaphone",
        permission: "ads.view",
      },
      {
        id: "home_banners",
        label: "Home Banners & Hero Showcase",
        route: "/admin/banners",
        iconName: "Image",
        badge: "FEATURED",
        badgeColor: "indigo",
        permission: "ads.view",
      },
    ],
  },
  {
    groupTitle: "Safety & Communication",
    items: [
      {
        id: "chat_monitoring",
        label: "Live Chat Monitor",
        route: "/admin/chat-monitoring",
        iconName: "MessageCircle",
        permissions: ["safety.view", "communication.view"],
        badge: "LIVE",
        badgeColor: "success",
      },
      {
        id: "safety",
        label: "Safety & Investigations",
        route: "/admin/safety-reports",
        iconName: "ShieldAlert",
        permissions: ["safety.view", "safety.investigate"],
        badge: 8,
        badgeColor: "error",
      },
      {
        id: "reviews",
        label: "Reviews & Ratings",
        route: "/admin/reviews",
        iconName: "Star",
        permission: "reviews.view",
      },
      {
        id: "support",
        label: "Support Desk",
        route: "/admin/support",
        iconName: "HelpCircle",
        permission: "support.view",
        badge: 67,
        badgeColor: "warning",
      },
    ],
  },
  {
    groupTitle: "Platform & Governance",
    items: [
      {
        id: "notifications",
        label: "Notifications & Push",
        route: "/admin/notifications",
        iconName: "Bell",
        permission: "notifications.view",
      },
      {
        id: "analytics",
        label: "Analytics & Reports",
        route: "/admin/analytics",
        iconName: "BarChart3",
        permission: "analytics.view",
      },
      {
        id: "audit",
        label: "System Audit Logs",
        route: "/admin/audit-logs",
        iconName: "History",
        permission: "audit.view",
      },
      {
        id: "administration",
        label: "Roles & System Settings",
        route: "/admin/roles",
        iconName: "Settings",
        permissions: ["admins.view", "roles.view", "audit.view", "settings.view"],
      },
    ],
  },
];
